apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: topology-aware-standard
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-volume-claim
  labels:
    app: neo4j-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #storageClassName: topology-aware-standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-plugin-volume-claim
  labels:
    app: neo4j-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  #storageClassName: topology-aware-standard
