apiVersion: apps/v1
kind: Deployment
metadata:
  name: docsund-ui
  labels:
    app: docsund-ui
spec:
  selector:
    matchLabels:
      app: docsund-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: docsund-ui
    spec:
      containers:
        - name: docsund-ui
          image: acarl005/docsund-ui:0.1.14
          ports:
            - containerPort: 1234
      nodeSelector:
        group: workers
