apiVersion: apps/v1
kind: Deployment
metadata:
  name: topics-api
  labels:
    app: topics-api
spec:
  selector:
    matchLabels:
      app: topics-api
  replicas: 1
  template:
    metadata:
      labels:
        app: topics-api
    spec:
      containers:
        - name: docsund-topics-api
          image: acarl005/docsund-topics-api:0.1.6
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: topics-volume
              mountPath: /app/state
      volumes:
        - name: topics-volume
          persistentVolumeClaim:
            claimName: topics-volume-claim
      nodeSelector:
        group: workers
