#!/bin/bash -xe

minikube start --cpus 4 --memory 8192 --disk-size 30g

# need these steps to fix an issue with elasticsearch
minikube ssh 'echo "sysctl -w vm.max_map_count=262144" | sudo tee -a /var/lib/boot2docker/bootlocal.sh'
minikube stop && minikube start

# not really necessary locally, just to match the AWS deployment, where this selector is actually necessary
# for volume affinity reasons
kubectl label node minikube group=workers
