apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:6.8.1
          resources:
            requests:
              cpu: 1
              memory: 1Gi
              ephemeral-storage: 8Gi
          ports:
            - containerPort: 9200
              name: main
            - containerPort: 9300
              name: peer
      nodeSelector:
        group: workers
