apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-database
  labels:
    app: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j-database
          image: neo4j
          env:
            # this config is necessary for the PageRank plugin to work
            - name: NEO4J_dbms_security_procedures_unrestricted
              value: algo.*
            - name: NEO4J_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-secrets
                  key: password
            - name: NEO4J_AUTH
              value: neo4j/$(NEO4J_DATABASE_PASSWORD)
          resources:
            requests:
              cpu: 1
              memory: 512Mi
          ports:
            - containerPort: 7474
              name: admin
            - containerPort: 7687
              name: main
          volumeMounts:
            - name: neo4j-data-volume
              mountPath: /data
            - name: neo4j-plugin-volume
              mountPath: /plugins
      nodeSelector:
        group: workers
      volumes:
        - name: neo4j-data-volume
          persistentVolumeClaim:
            claimName: neo4j-data-volume-claim
        - name: neo4j-plugin-volume
          persistentVolumeClaim:
            claimName: neo4j-plugin-volume-claim
